language: node_js
node_js:
  - "5.0"
  - "4.2"
  - "0.12"
  - "0.10"
  - "0.8"
before_install:
  - "npm install -g npm@next"
  - "npm install -g mocha crc-32 benchmark ansi"
  - "npm install blanket"
  - "npm install coveralls mocha-lcov-reporter"
after_success:
  - "make coveralls-spin"
  - "make perf-all"
